/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import exceptions.InvalidDNIException;
import exceptions.InvalidNameException;
import ficheros.ClassFichero;
import model.validations.UserDataValidations;

/**
 *
 * @author xavierortcol
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLableTitle = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonValidate = new javax.swing.JButton();
        jLabelErrName = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDNI1 = new javax.swing.JLabel();
        jTextFieldBirthdate = new javax.swing.JTextField();
        jLabelDNI2 = new javax.swing.JLabel();
        jLabelDNI3 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldZIP = new javax.swing.JTextField();
        jLabelDNI4 = new javax.swing.JLabel();
        jLabelErrDNI = new javax.swing.JLabel();
        jLabelErrEmail = new javax.swing.JLabel();
        jLabelErrAge = new javax.swing.JLabel();
        jLabelErrBirthdate = new javax.swing.JLabel();
        jLabelErrZIP = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLableTitle.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLableTitle.setForeground(new java.awt.Color(0, 0, 255));
        jLableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLableTitle.setText("VALIDAR DATOS USUARIO");
        jLableTitle.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelDNI.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDNI.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDNI.setText("DNI:");

        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/Sin título.png"))); // NOI18N

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jLabelErrName.setForeground(new java.awt.Color(255, 0, 0));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelDNI1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDNI1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDNI1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDNI1.setText("Email:");

        jTextFieldBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdateActionPerformed(evt);
            }
        });

        jLabelDNI2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDNI2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDNI2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDNI2.setText("Birthdate:");

        jLabelDNI3.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDNI3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDNI3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDNI3.setText("Age:");

        jTextFieldAge.setEditable(false);
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        jTextFieldZIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZIPActionPerformed(evt);
            }
        });

        jLabelDNI4.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDNI4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDNI4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDNI4.setText("ZIP:");

        jLabelErrDNI.setBackground(new java.awt.Color(255, 255, 255));
        jLabelErrDNI.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelErrEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrAge.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrBirthdate.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrZIP.setForeground(new java.awt.Color(255, 0, 0));

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setText("csv");
        jButtonCSV.setEnabled(false);
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelDNI)
                                    .addComponent(jLabelDNI1)
                                    .addComponent(jLabelDNI2)
                                    .addComponent(jLabelDNI3)
                                    .addComponent(jLabelDNI4))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDNI)
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jTextFieldBirthdate)
                                    .addComponent(jTextFieldAge)
                                    .addComponent(jTextFieldZIP))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelErrDNI)
                                    .addComponent(jLabelErrEmail)
                                    .addComponent(jLabelErrAge)
                                    .addComponent(jLabelErrZIP)
                                    .addComponent(jLabelErrBirthdate)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonValidate)
                                .addGap(107, 107, 107)
                                .addComponent(jButtonClear)
                                .addGap(95, 95, 95)
                                .addComponent(jButtonCSV)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelLogo)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI)
                    .addComponent(jLabelErrDNI))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI1)
                    .addComponent(jLabelErrEmail))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI2)
                    .addComponent(jLabelErrBirthdate))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI3)
                    .addComponent(jLabelErrAge))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNI4)
                    .addComponent(jLabelErrZIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidate)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCSV))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        String Name = jTextFieldName.getText();
        String NIF = jTextFieldDNI.getText();
        String Email = jTextFieldEmail.getText();
        String Birth = jTextFieldBirthdate.getText();
        String ZIP = jTextFieldZIP.getText();
        int age = 0;
        boolean error = false;

        try {
            UserDataValidations.checkName(Name);  // Llamamos a la función de validación del nombre
            jTextFieldName.setEditable(false);
            jLabelErrName.setText("");  // Limpiar el mensaje de error si el nombre es válido
        } catch (InvalidNameException ex) {
            jLabelErrName.setText(ex.getMessage());  // Mostrar el mensaje de la excepción en el label de error
            error = true;
        }

        
        try {
            UserDataValidations.checkId(1, NIF);  // Verificamos el NIF
            jTextFieldDNI.setEditable(false);
            jLabelErrDNI.setText("");  // Limpiar el mensaje de error si el NIF es válido
        } catch (InvalidDNIException ex) {
            jLabelErrDNI.setText(ex.getMessage());  // Mostrar el mensaje de la excepción en el label de error
            error = true;
        }

        if (!UserDataValidations.checkEmail(Email)) {
            jLabelErrEmail.setText("incorrect e-mail!");
            error = true;
        } else {
            jTextFieldEmail.setEditable(false);
            jLabelErrEmail.setText("");
        }

        if (!UserDataValidations.checkFormatDate(Birth)) {
            jLabelErrBirthdate.setText("incorrect birthday!");
            error = true;
        } else {
            age = UserDataValidations.calculateAge(Birth);
            jTextFieldAge.setText(String.valueOf(age));
            jTextFieldAge.setEditable(false);
            jTextFieldBirthdate.setEditable(false);
            jLabelErrBirthdate.setText("");
        }

        if (!UserDataValidations.checkPostalCode(ZIP)) {
            jLabelErrZIP.setText("incorrect ZIP!");
            error = true;
        } else {
            jTextFieldZIP.setEditable(false);
            jLabelErrZIP.setText("");
        }

        jButtonCSV.setEnabled(!error);

        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdateActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldZIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZIPActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        String Name = jTextFieldName.getText();
        String NIF = jTextFieldDNI.getText();
        String Email = jTextFieldEmail.getText();
        String Birth = jTextFieldBirthdate.getText();
        String ZIP = jTextFieldZIP.getText();
        String Age = jTextFieldAge.getText();

        String line = Name + ";" + NIF + ";" + Email + ";" + Birth + ";" + ZIP + ";" + Age + ";";
        ClassFichero.writeFile(line);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldName.setText("");
        jTextFieldDNI.setText("");
        jTextFieldEmail.setText(" private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {                                           \n"
                + "    String Name = jTextFieldName.getText();\n"
                + "        String NIF = jTextFieldDNI.getText();\n"
                + "        String Email = jTextFieldEmail.getText();\n"
                + "        String Birth = jTextFieldBirthdate.getText();\n"
                + "        String ZIP = jTextFieldZIP.getText();\n"
                + "        String Age = jTextFieldAge.getText();\n"
                + " \n"
                + "        String line = Name + \";\" + NIF + \";\" + Email + \";\" + Birth + \";\" + ZIP + \";\" + Age + \";\";\n"
                + "        ClassFichero.writeFile(line);        // TODO add your handling code here:\n"
                + "    }                                          \n"
                + "");
        jTextFieldBirthdate.setText("");
        jTextFieldZIP.setText("");
        jTextFieldAge.setText("");
        jTextFieldZIP.setText("");
        jLabelErrName.setText("");
        jLabelErrDNI.setText("");
        jLabelErrEmail.setText("");
        jLabelErrBirthdate.setText("");        // TODO add your handling code here:
        jLabelErrZIP.setText("");
        jTextFieldName.setEditable(true);
        jTextFieldDNI.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldBirthdate.setEditable(true);
        jTextFieldZIP.setEditable(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNI1;
    private javax.swing.JLabel jLabelDNI2;
    private javax.swing.JLabel jLabelDNI3;
    private javax.swing.JLabel jLabelDNI4;
    private javax.swing.JLabel jLabelErrAge;
    private javax.swing.JLabel jLabelErrBirthdate;
    private javax.swing.JLabel jLabelErrDNI;
    private javax.swing.JLabel jLabelErrEmail;
    private javax.swing.JLabel jLabelErrName;
    private javax.swing.JLabel jLabelErrZIP;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLableTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthdate;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZIP;
    // End of variables declaration//GEN-END:variables
}
